"""Simple data transferred between the renderer's hardware-like blocks."""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Iterator, TypeAlias

import numpy as np
from numpy.typing import NDArray

FloatArray: TypeAlias = NDArray[np.float64]
IntArray: TypeAlias = NDArray[np.int64]
Color: TypeAlias = tuple[int, int, int]


@dataclass(frozen=True)
class Mesh:
    """Local-space homogeneous vertices and explicit drawable edge indices."""

    vertices: FloatArray
    edges: IntArray
    color: Color = (255, 255, 255)
    triangles: IntArray | None = None


@dataclass(frozen=True)
class SceneObject:
    """A mesh instance and its local-to-world transform."""

    mesh: Mesh
    model_matrix: FloatArray = field(default_factory=lambda: np.eye(4, dtype=np.float64))
    name: str = "object"


@dataclass(frozen=True)
class Scene:
    """Ordered collection of objects, matching deterministic ROM traversal."""

    objects: tuple[SceneObject, ...]

    def __iter__(self) -> Iterator[SceneObject]:
        return iter(self.objects)


@dataclass(frozen=True)
class Camera:
    """Camera pose in world space; rotations are XYZ radians."""

    position: FloatArray = field(default_factory=lambda: np.zeros(3, dtype=np.float64))
    rotation_xyz: FloatArray = field(default_factory=lambda: np.zeros(3, dtype=np.float64))


@dataclass(frozen=True)
class LinePrimitive:
    """Untransformed endpoints plus instance metadata issued by geometry fetch."""

    v0: FloatArray
    v1: FloatArray
    color: Color
    model_matrix: FloatArray


@dataclass(frozen=True)
class Pixel:
    """One integer framebuffer write generated by the line rasterizer."""

    x: int
    y: int
    color: Color
